service: beenion-write-side

plugins:
  - serverless-webpack

custom:
  webpack: ./webpack.config.${opt:debug, 'prod'}.js

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  region: us-east-1
  environment:
    TOKEN_ISSUER: https://beenion.auth0.com/
    JWKS_URI: https://beenion.auth0.com/.well-known/jwks.json
    AUDIENCE: http://rsapi
    EVENTSTORE_TABLE: EventStoreDB-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.EVENTSTORE_TABLE}"

functions:
  auth:
    handler: src/auth0-authorizer.auth
    cors: true
  command:
    handler: src/command.handler
    events:
      - http:
          cors: true
          path: api/command
          method: post
          authorizer: auth

resources:
  Resources:
    EventStoreTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.EVENTSTORE_TABLE}
        AttributeDefinitions: ${file(../repositories/dynamodb/adapter/schema.json):AttributeDefinitions}
        KeySchema: ${file(../repositories/dynamodb/adapter/schema.json):KeySchema}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5