service: user-pool-postconfirmation

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminUpdateUserAttributes
      Resource: "arn:aws:cognito-idp:us-east-1:862859958676:userpool/us-east-1_uSqXNHQwb"

functions:
  preTokenGeneration:
    handler: preTokenGeneration.handler
  postConfirmation:
    handler: postConfirmation.handler
    ##
    # commented because of issue https://github.com/serverless/serverless/issues/4207
    # trigger is currently signed manually in user pool dashboard
    #
    # events:
    #   - cognitoUserPool:
    #       pool: "arn:aws:cognito-idp:us-east-1:862859958676:userpool/us-east-1_uSqXNHQwb"
    #       trigger: PostConfirmation
  
